// SPDX-License-Identifier: Apache-2.0
//
// Copyright © 2025 The Happy Authors

package l10n

import (
	"strings"
	"testing"

	"github.com/happy-sdk/happy/pkg/i18n"
	"golang.org/x/text/language"
)

func TestExportedFuncName(t *testing.T) {
	cases := []struct {
		bundle, key, want string
	}{
		{"com.github.example.app", "com.github.example.app.help.description", "HelpDescription"},
		{"com.github.example.app", "com.github.example.app.greeting", "Greeting"},
		{"app", "app.flag_with_deps", "FlagWithDeps"},
		{"app", "app", "Message"},
		{"app", "app.2fa_prompt", "M2faPrompt"},
	}
	for _, c := range cases {
		got := exportedFuncName(c.bundle, c.key)
		if got != c.want {
			t.Errorf("exportedFuncName(%q, %q) = %q, want %q", c.bundle, c.key, got, c.want)
		}
	}
}

func TestGoTypeForArgType(t *testing.T) {
	cases := []struct {
		t    i18n.ArgType
		want string
	}{
		{i18n.ArgTypeString, "string"},
		{i18n.ArgTypeDecimal, "int"},
		{i18n.ArgTypeFloat, "float64"},
		{i18n.ArgTypeNumber, "float64"},
		{i18n.ArgTypeTruth, "bool"},
		{i18n.ArgTypeCurrency, "currency.Amount"},
		{i18n.ArgTypeAny, "any"},
		{i18n.ArgTypeUnknown, "any"},
	}
	for _, c := range cases {
		if got := goTypeForArgType(c.t); got != c.want {
			t.Errorf("goTypeForArgType(%v) = %q, want %q", c.t, got, c.want)
		}
	}
}

func TestGenerateTypedAccessors_Fixture(t *testing.T) {
	keys := []genKey{
		{Key: "com.github.example.app.greeting", Args: []genArg{{Name: "name", GoType: "string"}}},
		{Key: "com.github.example.app.items", Args: []genArg{{Name: "count", GoType: "int"}}},
		{Key: "com.github.example.app.welcome"}, // no args
	}
	src, err := generateTypedAccessors("messages", "com.github.example.app", keys)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	got := string(src)

	wants := []string{
		"// Code generated by \"l10n generate\"; DO NOT EDIT.",
		"package messages",
		`import "github.com/happy-sdk/happy/pkg/i18n"`,
		"func Greeting(name string) string {",
		`return i18n.T("com.github.example.app.greeting", "name", name)`,
		"func Items(count int) string {",
		`return i18n.T("com.github.example.app.items", "count", count)`,
		"func Welcome() string {",
		`return i18n.T("com.github.example.app.welcome")`,
	}
	for _, w := range wants {
		if !strings.Contains(got, w) {
			t.Errorf("generated source missing %q\n---\n%s", w, got)
		}
	}

	// Deterministic ordering: Greeting < Items < Welcome by key.
	gi := strings.Index(got, "func Greeting")
	ii := strings.Index(got, "func Items")
	wi := strings.Index(got, "func Welcome")
	if !(gi < ii && ii < wi) {
		t.Errorf("expected accessors ordered by key, got positions Greeting=%d Items=%d Welcome=%d", gi, ii, wi)
	}
}

func TestGenerateTypedAccessors_KeywordArgNameIsEscaped(t *testing.T) {
	// Real-world case: pkg/i18n's own error.unsupported_type key has an arg
	// literally named "type" - using it verbatim as a Go parameter name is a
	// hard syntax error ("type" is a keyword). The generated Go must still
	// compile/gofmt, and the key string passed to i18n.T must stay "type"
	// unescaped - only the local Go variable name is escaped.
	keys := []genKey{
		{Key: "com.github.example.app.error.unsupported_type", Args: []genArg{
			{Name: "key", GoType: "string"},
			{Name: "lang", GoType: "string"},
			{Name: "type", GoType: "string"},
		}},
	}
	src, err := generateTypedAccessors("messages", "com.github.example.app", keys)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	got := string(src)

	if !strings.Contains(got, "type_ string") {
		t.Errorf("expected the \"type\" arg's Go parameter to be escaped to \"type_\", got:\n%s", got)
	}
	if !strings.Contains(got, `"type", type_`) {
		t.Errorf("expected the i18n.T call to pass the literal key \"type\" alongside the escaped type_ variable, got:\n%s", got)
	}
}

// TestGenerateTypedAccessors_CurrencyImport is a regression test for a bug
// where a {name:currency} arg generated a "string" parameter - a type the
// runtime currency verb can never actually format (it only accepts a real
// currency.Amount; anything else renders a visible "%!currency" mismatch
// marker). The generated accessor must take a currency.Amount and the file
// must import golang.org/x/text/currency to make that type available.
func TestGenerateTypedAccessors_CurrencyImport(t *testing.T) {
	keys := []genKey{
		{Key: "com.github.example.app.price", Args: []genArg{
			{Name: "amount", GoType: goTypeForArgType(i18n.ArgTypeCurrency)},
		}},
	}
	src, err := generateTypedAccessors("messages", "com.github.example.app", keys)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	got := string(src)
	if !strings.Contains(got, `"golang.org/x/text/currency"`) {
		t.Errorf("expected the golang.org/x/text/currency import, got:\n%s", got)
	}
	if !strings.Contains(got, "amount currency.Amount") {
		t.Errorf("expected a currency.Amount parameter, got:\n%s", got)
	}
}

// TestGenerateTypedAccessors_NoCurrencyImportWhenUnused confirms the currency
// import is only added when actually needed - a bundle with no currency args
// must not import a package it never references (an unused-import compile
// error would be worse than the bug this whole fix is closing).
func TestGenerateTypedAccessors_NoCurrencyImportWhenUnused(t *testing.T) {
	keys := []genKey{
		{Key: "com.github.example.app.greeting", Args: []genArg{{Name: "name", GoType: "string"}}},
	}
	src, err := generateTypedAccessors("messages", "com.github.example.app", keys)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(string(src), "x/text/currency") {
		t.Errorf("did not expect a currency import when no key uses one, got:\n%s", src)
	}
}

func TestGenerateTypedAccessors_BlankIdentifierArgIsEscaped(t *testing.T) {
	// "_" is a legal {name:verb} placeholder name (named.go's
	// namedPlaceholderRe allows a leading underscore) but not a keyword, and
	// not usable as a value - "_" can't appear on the right-hand side of an
	// expression, so a naive `i18n.T(key, "_", _)` fails to compile.
	keys := []genKey{
		{Key: "com.github.example.app.blank", Args: []genArg{{Name: "_", GoType: "string"}}},
	}
	src, err := generateTypedAccessors("messages", "com.github.example.app", keys)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	got := string(src)
	if !strings.Contains(got, "__ string") {
		t.Errorf("expected the \"_\" arg's Go parameter to be escaped, got:\n%s", got)
	}
	if !strings.Contains(got, `"_", __`) {
		t.Errorf("expected the i18n.T call to pass the literal key \"_\" alongside the escaped __ variable, got:\n%s", got)
	}
}

func TestGenerateTypedAccessors_NameCollisionIsRejected(t *testing.T) {
	// "foo.bar_baz" and "foo.bar.baz" both CamelCase to "FooBarBaz" -
	// undetected, that's a "FooBarBaz redeclared" compile error in the
	// generated file with no indication of which two keys caused it.
	keys := []genKey{
		{Key: "com.github.example.app.foo.bar_baz"},
		{Key: "com.github.example.app.foo.bar.baz"},
	}
	_, err := generateTypedAccessors("messages", "com.github.example.app", keys)
	if err == nil {
		t.Fatal("expected an error for two keys colliding on the same generated function name")
	}
	if !strings.Contains(err.Error(), "FooBarBaz") {
		t.Errorf("expected the error to name the colliding function, got: %v", err)
	}
}

// TestGenerateTypedAccessors_FromRegisteredBundle exercises the full path:
// register a small v2 bundle, derive typed keys via the i18n arg-type accessor,
// and generate compiling Go source.
func TestGenerateTypedAccessors_FromRegisteredBundle(t *testing.T) {
	i18n.Initialize(language.English)
	err := i18n.RegisterTranslations(language.Und, map[string]any{
		"version": float64(2),
		"bundle":  "com.github.example.gentest",
		"source":  "en",
		"locales": map[string]any{
			"en": map[string]any{"keys": map[string]any{
				"hello": map[string]any{"$message": map[string]any{"msg": "hi {name:s}, you have {count:d} messages"}},
				"plain": map[string]any{"$message": map[string]any{"msg": "just plain"}},
			}},
		},
	})
	if err != nil {
		t.Fatalf("register: %v", err)
	}
	src, ok := i18n.GetBundleSourceLanguage("com.github.example.gentest")
	if !ok || src != language.English {
		t.Fatalf("expected known English source language, got %v ok=%v", src, ok)
	}
	keys := collectBundleKeys("com.github.example.gentest", src)
	if len(keys) != 2 {
		t.Fatalf("expected 2 keys, got %d: %+v", len(keys), keys)
	}
	out, gerr := generateTypedAccessors("messages", "com.github.example.gentest", keys)
	if gerr != nil {
		t.Fatalf("generate: %v", gerr)
	}
	s := string(out)
	for _, w := range []string{"func Hello(count int, name string) string {", "func Plain() string {"} {
		if !strings.Contains(s, w) {
			t.Errorf("missing %q in:\n%s", w, s)
		}
	}
}

// TestGenerateTypedAccessors_FragmentDiscriminatorIncluded is an end-to-end
// regression test for a bug where a fragment's own discriminating arg (e.g. a
// select fragment's "gender", or a plural fragment's count when it's never
// displayed as text) was silently absent from the generated accessor's
// parameter list, since Message.ArgTypes() didn't report it. The generated
// function compiled and gofmted fine, but had no way to receive the value
// that selects the fragment's wording - it could only ever render "other".
// Fixed at the source (pkg/i18n's collectArgVerbs now always accounts for
// every fragment's Arg); this test exercises the fix through the real
// register -> collectBundleKeys -> generateTypedAccessors path so a
// regression here would be caught the same way the original bug should have
// been.
func TestGenerateTypedAccessors_FragmentDiscriminatorIncluded(t *testing.T) {
	i18n.Initialize(language.English)
	err := i18n.RegisterTranslations(language.Und, map[string]any{
		"version": float64(2),
		"bundle":  "com.github.example.fragtest",
		"source":  "en",
		"locales": map[string]any{
			"en": map[string]any{"keys": map[string]any{
				"greeting": map[string]any{"$message": map[string]any{
					"msg": "{g}",
					"fragments": map[string]any{
						"g": map[string]any{
							"kind": "select", "arg": "gender",
							"male": "he", "female": "she", "other": "they",
						},
					},
				}},
			}},
		},
	})
	if err != nil {
		t.Fatalf("register: %v", err)
	}
	src, ok := i18n.GetBundleSourceLanguage("com.github.example.fragtest")
	if !ok {
		t.Fatal("expected known source language")
	}
	keys := collectBundleKeys("com.github.example.fragtest", src)
	if len(keys) != 1 || len(keys[0].Args) != 1 || keys[0].Args[0].Name != "gender" {
		t.Fatalf("expected exactly one key with a \"gender\" arg, got %+v", keys)
	}
	out, gerr := generateTypedAccessors("messages", "com.github.example.fragtest", keys)
	if gerr != nil {
		t.Fatalf("generate: %v", gerr)
	}
	if !strings.Contains(string(out), "func Greeting(gender any) string {") {
		t.Errorf("expected a gender parameter on the generated accessor, got:\n%s", out)
	}
}
