version: "1"

releaser:
  enabled: true

deps:
  go:
    latest:
      - charm.land/bubbles/v2
      - charm.land/bubbletea/v2
      - charm.land/lipgloss/v2
      - github.com/fsnotify/fsnotify
      - codeberg.org/go-pdf/fpdf

git:
  author:
    email: hello@happy-sdk.dev
    name: The Happy Authors
  branch: main
  remote:
    url: git@github.com:happy-sdk/happy.git

ignore:
  - pkg/logging/internal/bench
