# https://taskfile.dev

version: "3"

dotenv: [".env"]

# Coverage
# Single package coverage
# - go test -coverprofile=coverage.out . && go tool cover -html=coverage.out -o coverage.html
tasks:
  lint:
    desc: Lint the project
    dir: .
    silent: true
    cmds:
      - bash ./.github/actions/golangci-lint-monorepo-action/golangci-lint-monorepo-action.sh
  test:
    desc: Test all project modules
    dir: .
    silent: true
    cmds:
      - bash ./.github/actions/go-test-monorepo-action/go-test-monorepo-action.sh

  test:win:
    desc: Test all project modules (Windows)
    dir: .
    silent: true
    cmds:
      - pwsh -File ./.github/actions/go-test-monorepo-action/go-test-monorepo-action.ps1

  release:
    desc: Run monorepo releaser
    dir: sdk/internal/cmd/hsdk
    silent: true
    cmds:
      - go run . release
