name: "Go Lint Monorepo"
description: "Run golangci-lint on a monorepo with multiple Go modules"
inputs:
  golangci-lint-version:
    description: "GolangCI-Lint version"
    required: true
    default: "v2.12.2"
  go-version:
    description: "The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks."
    required: true
    default: ">=1.26.0"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install golangci-lint
      shell: bash
      run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@${{ inputs.golangci-lint-version }}

    - name: Setup project
      shell: bash
      run: |
        git config --global user.email "happy-sdk@happy-sdk.dev"
        git config --global user.name "Happy SDK"

    - name: Install gohappy
      shell: bash
      run: go install github.com/happy-sdk/cmd/gohappy@v0.2.0

    - name: Lint all modules
      shell: bash
      run: script -q -e -c "gohappy --system-debug -x lint" /dev/stdout
