name: "Go Lint Monorepo"
description: "Run golangci-lint on a monorepo with multiple Go modules"
inputs:
  golangci-lint-version:
    description: "GolangCI-Lint version"
    required: true
    default: "latest"
  go-version:
    description: "The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks."
    required: true
    default: ">=1.23.0"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin ${{ inputs.golangci-lint-version }}
      shell: bash

    - name: Setup project
      shell: bash
      run: |
        git config --global user.email "happy-sdk@happy-sdk.dev"
        git config --global user.name "Happy SDK"

    - name: Install gohappy
      shell: bash
      run: go install github.com/happy-sdk/cmd/gohappy@v0.1.6

    - name: Lint all modules
      shell: bash
      run: gohappy --system-debug -x lint
